name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: yarn install --frozen-lockfile

    - name: build production deploy artifacts
      env:
        VITE_GITHUB_ARCHIVE_URL: ${{ github.server_url }}/${{ github.repository }}/archive/${{ github.sha }}.zip
      run: yarn build:production

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./dist

  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: ci

    # Allow one concurrent deployment
    concurrency:
      group: 'pages'
      cancel-in-progress: true

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/deploy-pages@v1
      id: deployment
