name: Upgrade dependencies

on: workflow_dispatch

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: upgrade dependencies
      run: pnpm upgrade --latest

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "[Automated] upgrade dependencies"
        commit-message: "[Automated] upgrade dependencies"
        branch: "auto/deps-upgrade"
        add-paths: |
          package.json
          pnpm-lock.yaml
        delete-branch: true
        labels: |
            automated pr
